//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataBaseFirst.WebApi.EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdoTable2
    {
        public int Id { get; set; }
        public string Work { get; set; }
        public Nullable<int> Position { get; set; }
    }
}
